import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowIcon, CheckIcon } from "@/components/icons";

const pages = {
  about: { kicker: "Our story", title: "Comfort, with a sense of place.", intro: "Qotun is an Egyptian home-linen brand born from years spent creating beautiful stays.", sections: [{ heading: "From hotels to home", text: "Our founders learned comfort from the inside—across hotels, premium stays, and the demanding daily rhythm of hospitality. Qotun brings that knowledge home through considered linens that feel exceptional, perform reliably, and remain accessible." }, { heading: "Proudly Egyptian", text: "We work with 100% premium Egyptian cotton, choosing the right weave and thread count for each purpose. The result is not luxury for show, but luxury you can feel every day." }] },
  "partner-with-qotun": { kicker: "Qotun Hospitality", title: "Better stays begin with better rest.", intro: "Premium, dependable linen solutions for boutique hotels, serviced apartments, spas, and design-led spaces.", sections: [{ heading: "Designed around your operation", text: "We supply different quality tiers and flexible quantities—from a few rooms to full-property openings—with practical guidance grounded in real hotel laundry experience." }, { heading: "Made to perform", text: "Our linens are tested through repeat wash cycles for lasting softness, strength, and an elevated guest experience. Every order includes support and a warranty against manufacturing defects." }] },
  "delivery-policy": { kicker: "Qotun care", title: "Delivery, handled with care.", intro: "We work with trusted courier partners so every Qotun piece reaches you carefully and on time.", sections: [{ heading: "When will my order arrive?", text: "Orders within Cairo usually arrive in 2–3 business days. For the rest of Egypt, please allow up to 5 business days. Every order is prepared and dispatched within one business day." }, { heading: "Shipping fees", text: "Delivery is complimentary on orders above 3,000 EGP. A standard fee applies below this amount and will be shown clearly at checkout." }] },
  "return-policy": { kicker: "Qotun care", title: "Returns should feel simple.", intro: "If you are not completely happy with your Qotun experience, we will help find the right solution.", sections: [{ heading: "Our 14-day promise", text: "Products can be returned or exchanged within 14 days of delivery when unused, unwashed, with original tags intact and the invoice included." }, { heading: "Refunds & defects", text: "Manufacturing defects are always handled immediately. Approved refunds are processed to the original payment method within 5–7 business days." }] },
  "terms-conditions": { kicker: "The details", title: "Terms & conditions.", intro: "Clear information about using Qotun’s website and services.", sections: [{ heading: "Website use", text: "Use of this website and transactions made through it are governed by the laws of Egypt. Customers must be at least 18 years old to register or transact." }, { heading: "Privacy & payments", text: "Personal information is collected only when voluntarily provided for orders, support, or subscribed communications. Payment details are transmitted directly to our secure payment provider." }] },
  faq: { kicker: "Qotun care", title: "A little help goes a long way.", intro: "Answers to the questions we are asked most often.", sections: [{ heading: "How do I choose a thread count?", text: "Think of thread count as character, not a score. Our 200-count cotton feels crisp and breathable, while 500-count cotton feels smoother and more substantial." }, { heading: "How should I care for my Qotun linens?", text: "Machine wash cool with similar colours, use a mild detergent, and tumble dry low. Avoid optical brighteners to preserve the natural cotton." }, { heading: "Can I exchange a size?", text: "Yes. Unused and unwashed pieces can be exchanged within 14 days of delivery. Our care team will guide you through it." }] },
  contact: { kicker: "Qotun care", title: "We’re here to help.", intro: "Questions about products, orders, delivery, returns—or simply making a better bed? Talk to us.", sections: [] },
} as const;

export function generateStaticParams() { return Object.keys(pages).map((slug) => ({ slug })); }

export default async function ContentPage({ params }: PageProps<"/pages/[slug]">) {
  const { slug } = await params;
  const page = pages[slug as keyof typeof pages];
  if (!page) notFound();
  const isContact = slug === "contact";
  const isB2B = slug === "partner-with-qotun";
  return <main className={`content-page ${isB2B ? "content-page--b2b" : ""}`}><header className="content-hero"><span className="eyebrow">{page.kicker}</span><h1>{page.title}</h1><p>{page.intro}</p></header><div className="content-body">{page.sections.map((section, index) => <section key={section.heading} className="reveal"><span>0{index + 1}</span><div><h2>{section.heading}</h2><p>{section.text}</p></div></section>)}{isB2B && <section className="b2b-points"><span>03</span><div><h2>Why partners choose Qotun</h2><ul><li><CheckIcon /> Flexible quantities and quality tiers</li><li><CheckIcon /> Hospitality-grade durability</li><li><CheckIcon /> Manufacturing warranty</li><li><CheckIcon /> Direct, personal support</li></ul><Link href="/pages/contact" className="button button-dark">Become a partner</Link></div></section>}{isContact && <section className="contact-layout"><div><div><span>Call or WhatsApp</span><a href="tel:+201035008335">+20 103 500 8335</a></div><div><span>Email</span><a href="mailto:qotun2025@gmail.com">qotun2025@gmail.com</a></div><div><span>Care hours</span><p>Saturday–Thursday<br />10:00–18:00 Cairo</p></div></div><form><div className="field-row"><label>Name<input name="name" placeholder="Your name" /></label><label>Email<input name="email" type="email" placeholder="you@example.com" /></label></div><label>Phone<input name="phone" placeholder="+20" /></label><label>How can we help?<textarea name="message" rows={5} placeholder="Tell us a little more…" /></label><button type="button" className="button button-dark">Send enquiry <ArrowIcon size={16} /></button></form></section>}</div></main>;
}
